### ISSUE TITLE
Implement CloudWatch cron job for SendSMS lambda

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Coronalert#34]
- [x] implement CloudWatch cron job to trigger the SendSMS lambda and send SMS notifications to users in the database
- [x] users should get notifications either every 4 hours, or just at 9, noon, and 4 so as to not bug then. Open to suggestions here!

**Comment by acthelemann** [comment]
@SomeMoosery 9, noon, and 4 ET sound good for now?

**Comment by SomeMoosery** [comment]
Sounds good to me 👍
