### ISSUE TITLE
Encrypt MongoDB URI for unsubscribe

### ISSUE THREAD

**Issue by tylerd92** [COVID-19-electronic-health-system/Coronalert#39]
Since the other lambdas use an encrypted MongoDB, I believe the unsubscribe lambda should have this as well.

**Comment by acthelemann** [comment]
@tylerd92 Are you working on this?

**Comment by tylerd92** [comment]
I haven't started yet. You can work on it if you want. I know encrypting the uri it involves AWS, I don't know the process exactly.
