### ISSUE TITLE
Deploy Dockerized environment to AWS EC2 instance behind an API Gateway

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Coronalert#8]
Once we have our service Dockerized, we need to spin it up on an EC2 instance behind an API Gateway. For now, we should be okay running on one EC2 instance, but we may have to consider adding an autoscaling group later.

**Comment by acthelemann** [comment]
@SomeMoosery Unnecessary?

**Comment by SomeMoosery** [comment]
yup :|
